---
title: "Maturity-at-age: comparison with historic values"
date: "`r Sys.Date()`"
output:
  html_document:
    toc: true
    toc_depth: 3
    toc_float:
      collapsed: FALSE
    code_folding: show
    number_sections: TRUE
---

# SET-UP

```{r markdown, echo=F}
library(knitr)
opts_chunk$set(echo = T, collapse = T, fig.align = "center", fig.width = 9, fig.height = 6,warning = FALSE, message = FALSE)
options(width = 300)
```    

```{r settings, message = F}
source('0.0_settings.R')
```

# load all data

```{r data, message = F}
# maa
repo <- "https://github.com/iml-mackerel/00.0_model/blob/master/"

ys <- c(2011,2013,2016,2018,2020)
maa.hist <- lapply(ys, function(x) read.ices(url(paste0(repo,'data/',x,'/mo.dat',"?raw=true"))))
names(maa.hist) <- ys 
```

# History {.tabset}
## changes
```{r plot hist,fig.width=10}
# reshape
maam <- lapply(names(maa.hist), function(x) reshape2::melt(as.matrix(maa.hist[[x]]),varnames=c('year','age'),value.name=x))
maa.comp <- Reduce(function(x, y) merge(x, y, all=TRUE), maam)
maa.comp <- maa.comp[order(maa.comp$year,maa.comp$age),]

# difference
maa.diff <- cbind(maa.comp[,c(1:2)],maa.comp[,3:ncol(maa.comp)]-maa.comp[,c(3,3:(ncol(maa.comp)-1))])
names(maa.diff)[3:ncol(maa.diff)] <- paste(names(maa.diff)[3:ncol(maa.diff)],c(names(maa.diff)[3],names(maa.diff)[3:(ncol(maa.diff)-1)]),sep=" - ")
maa.diff[,3] <- NULL

ggplot(melt(maa.diff,id=c('year','age')),aes(x=year,y=age,fill=value))+
    geom_tile(col='black')+
    facet_wrap(~variable)+
    scale_x_continuous(expand=c(0,0),limits=c(1967.5,2020.5))+
    scale_y_continuous(expand=c(0,0),breaks=c(1,5,10),labels=c(1,5,"10+"))+
    theme(axis.text.x = element_text(angle=45,hjust=1))+
    scale_fill_gradient2(low=viridis(3)[1],high=viridis(3)[3],midpoint=0,mid = viridis(3)[2],na.value = 'transparent')+
    labs(fill='',x='Year',y='Age')
```